import type { Customer, InventoryItem, PackagePlan, Transaction } from './types';

const now = Date.now();

export const initialTransactions: Transaction[] = [
  {
    id: 'tx-1',
    type: 'income',
    amount: 250000,
    category: 'Penjualan Kopi',
    description: 'Penjualan kopi susu 10 cup',
    productName: 'Kopi Susu',
    customerId: 'c-1',
    customerName: 'Toko Maju',
    paymentMethod: 'qris',
    paid: true,
    timestamp: new Date(now - 60 * 60 * 1000),
  },
  {
    id: 'tx-2',
    type: 'expense',
    amount: 180000,
    category: 'Operasional',
    description: 'Beli gula dan susu',
    paymentMethod: 'transfer',
    paid: true,
    timestamp: new Date(now - 3 * 60 * 60 * 1000),
  },
  {
    id: 'tx-3',
    type: 'debt',
    amount: 320000,
    category: 'Piutang',
    description: 'Utang Pak Budi untuk order katering',
    customerId: 'c-2',
    customerName: 'Pak Budi',
    paymentMethod: 'cash',
    paid: false,
    timestamp: new Date(now - 26 * 60 * 60 * 1000),
  },
  {
    id: 'tx-4',
    type: 'income',
    amount: 460000,
    category: 'Penjualan Makanan',
    description: 'Order Shopee Food 24 item',
    productName: 'Keripik Pisang',
    customerId: 'c-3',
    customerName: 'Nadira Shop',
    paymentMethod: 'e-wallet',
    paid: true,
    timestamp: new Date(now - 28 * 60 * 60 * 1000),
  },
  {
    id: 'tx-5',
    type: 'expense',
    amount: 90000,
    category: 'Logistik',
    description: 'Ongkir suplai bahan',
    paymentMethod: 'cash',
    paid: true,
    timestamp: new Date(now - 48 * 60 * 60 * 1000),
  },
];

export const initialInventory: InventoryItem[] = [
  {
    id: 'i-1',
    name: 'Kopi Arabica',
    category: 'Bahan Baku',
    stock: 12,
    minStock: 15,
    price: 120000,
    dailyUsage: 3,
    movement: [
      { date: 'Sen', in: 8, out: 5 },
      { date: 'Sel', in: 0, out: 4 },
      { date: 'Rab', in: 10, out: 6 },
      { date: 'Kam', in: 0, out: 5 },
      { date: 'Jum', in: 0, out: 3 },
      { date: 'Sab', in: 0, out: 4 },
      { date: 'Min', in: 0, out: 5 },
    ],
  },
  {
    id: 'i-2',
    name: 'Keripik Pisang',
    category: 'Produk Jadi',
    stock: 85,
    minStock: 20,
    price: 18000,
    dailyUsage: 12,
    movement: [
      { date: 'Sen', in: 40, out: 10 },
      { date: 'Sel', in: 0, out: 12 },
      { date: 'Rab', in: 30, out: 14 },
      { date: 'Kam', in: 0, out: 12 },
      { date: 'Jum', in: 0, out: 11 },
      { date: 'Sab', in: 0, out: 13 },
      { date: 'Min', in: 0, out: 9 },
    ],
  },
  {
    id: 'i-3',
    name: 'Susu Oat',
    category: 'Bahan Baku',
    stock: 9,
    minStock: 12,
    price: 32000,
    dailyUsage: 2,
    movement: [
      { date: 'Sen', in: 6, out: 1 },
      { date: 'Sel', in: 0, out: 2 },
      { date: 'Rab', in: 3, out: 2 },
      { date: 'Kam', in: 0, out: 1 },
      { date: 'Jum', in: 0, out: 2 },
      { date: 'Sab', in: 0, out: 2 },
      { date: 'Min', in: 0, out: 1 },
    ],
  },
];

export const initialCustomers: Customer[] = [
  {
    id: 'c-1',
    name: 'Toko Maju',
    segment: 'Retail',
    notes: 'Prefer bayar QRIS, order tiap minggu.',
    totalSpending: 4200000,
    repeatOrders: 18,
    lastOrderAt: new Date(now - 24 * 60 * 60 * 1000),
  },
  {
    id: 'c-2',
    name: 'Pak Budi',
    segment: 'UMKM',
    notes: 'Sering ambil tempo 7 hari.',
    totalSpending: 1750000,
    repeatOrders: 7,
    lastOrderAt: new Date(now - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'c-3',
    name: 'Nadira Shop',
    segment: 'Online Shop',
    notes: 'Fokus TikTok Live bundling snack.',
    totalSpending: 5900000,
    repeatOrders: 23,
    lastOrderAt: new Date(now - 4 * 60 * 60 * 1000),
  },
];

export const packagePlans: PackagePlan[] = [
  {
    id: 'basic',
    name: 'BASIC',
    setupPrice: 999000,
    monthlyPrice: 79000,
    features: ['Website & Cashflow Sederhana', 'Domain .my.id', '1 Akun Admin'],
  },
  {
    id: 'pro',
    name: 'PRO',
    setupPrice: 1499000,
    monthlyPrice: 139000,
    features: ['Manajemen Stok & Pelanggan', 'Domain .com', 'Export PDF & Excel'],
  },
  {
    id: 'platinum',
    name: 'PLATINUM',
    setupPrice: 1999999,
    monthlyPrice: 189000,
    features: ['Analisis Bisnis Premium', 'Integrasi Payment Gateway', 'Hutang & Piutang'],
  },
];

